server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway


  cloud:
    gateway:
      routes:
        - id: xujin_route
          uri: http://www.qq.com:80/
          predicates:
            - Path=/xujin

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG